% 示例脚本：run_combined_plot_and_process_path.m

% 定义必要的文件路径
original_path_file = '\\wsl.localhost\Ubuntu\home\lhl\share\rip\scripts\landing_path_planning\VFRRT_Planner\path_e_05_lam_0011_sam_1000000\path_99.txt';
sampled_path_file = 'sample_path.txt';
main_directions_path = '/home/lhl/share/rip/scripts/landing_path_planning/vf_estimate/data/output/main_directions.mat';

% 定义可选参数
output_folder = 'output_data'; % 输出文件夹路径
sample_interval = 1; % 采样间隔为1米
figure_filename = 'path_with_tangents.png'; % 绘图文件名
angles_filename = 'tangent_angles.txt'; % 切向量夹角文件名
direction_differences_filename = 'direction_differences.txt'; % 方向差异文件名
scale_x = 1; % x 轴缩放因子
scale_y = 2; % y 轴缩放因子

% 调用 combined_plot_and_process_path 函数
combined_plot_and_process_path(...
    original_path_file, ...
    sampled_path_file, ...
    main_directions_path, ...
    'OutputFolder', output_folder, ...
    'SampleInterval', sample_interval, ...
    'FigureFilename', figure_filename, ...
    'AnglesFilename', angles_filename, ...
    'DirectionDifferencesFilename', direction_differences_filename, ...
    'ScaleX', scale_x, ...
    'ScaleY', scale_y ...
);
